### ISSUE TITLE
number of spells known per level

### ISSUE THREAD

**Issue by Red-Kai** [subtledoctor/mana_sorcerer#1]
I'm trying to change the number of spells mana sorcerer get per level .
I modified the splsrknw.2da in the mod folder , and reinstall the mod to no avail.

this worked for fresh install , but not when I'm reinstalling it ,I suspect the number of spells known per level is generated from splsrkwn.2da but later stored somewhere else , so making the change to 2da and reinstalling does not change it .

my questions is where are the know spell level stored (post installation) ?

thanks

**Comment by Red-Kai** [comment]
I should mention this is for SOD (ui is different)

**Comment by subtledoctor** [comment]
Try:
- uninstall
- edit “qd_splsrckn.2da”
- if that file doesn’t exist, edit “splsrckn.2da”
- install

(If you have a bunch if mods installed after this one, this becomes more complicated.)

**Comment by Red-Kai** [comment]
Thanks , 
I have tried this , and no dice for SOD/BG1EE  
mana socrere is the last mod . I:
1.Uninstalled
2.modified splsrckn.2da (in both the mod folder and the override) - no qd_splsrckn.2da after the mod is uninstalled.
3.reinstall 
4.spell selection is the same 

this worked for me when trying it on BG2EE - BUT I did it on a fresh installation

is there anything uniqe to SOD (different UI ?)
or , is the spell count saved somewhere as cached , or in the save file maybe ?

**Comment by Red-Kai** [comment]
just tried a new game , and I'm still seeing the old number of spells - so it's not related to the save game

**Comment by Red-Kai** [comment]
ok found the problem d5msorcX.2da is not deleted at uninstall so the TPA condition of creating the new list does not apply . the solution is to delete d5msorcX.2da from the override folder after uninstall .
